### ISSUE TITLE
Black background color

### ISSUE THREAD

**Issue by wangjia184** [shinokada/svelte-feathers#3]
### Describe the bug

![image](https://github.com/shinokada/svelte-feathers/assets/2765840/7b42f36d-3ed4-4069-b030-12494d10ef31)

As you can see from the above screenshot,  the icons are rendered with a black background. Perhaps it is because my web browser is configured to be dark theme (I am not sure).

How to avoid this?

### Reproduction

Open https://svelte-feathers.codewithshin.com/icons,  change to light mode

### Version and System Info

```shell
Chrome Version 125.0.6422.142 (Official Build) (64-bit)
Windows
```

**Comment by shinokada** [comment]
Thanks.
Please check v1.0.6.
